spring.application.name=API-Gateway
spring.config.import=classpath:routes.yml
rlaas.apikey=${RLAAS_API_KEY:dev-apikey}
eureka.client.service-url.defaultZone=http://service-discovery:8081/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
logging.file.path=logs
