spring.application.name=Sample-Microservice-1
server.port=8082
eureka.client.service-url.defaultZone=http://service-discovery:8081/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
